#ifndef __SYS_PLL_CLOCK_H__
#define __SYS_PLL_CLOCK_H__

#include "LL_base.h"
#include "LL_PRCM_def.h"

/* 
 * PRCM_SYS_CLOCK = SYS_PLL_CLOCK / M / N
 * SYS_PLL_CLOCK: 1920 MHz on XR872/XR808, 960 MHz on XR806
 * M: 5 ~ 9
 * N: 1 ~ 16
 */

#define LL_PRCM_SYSCLK_FACTORM_Pos  (8U)
#define LL_PRCM_SYSCLK_FACTORM_Msk  (0x7U << LL_PRCM_SYSCLK_FACTORM_Pos)
#define LL_PRCM_SYSCLK_FACTORM_Start LL_PRCM_SYSCLK_FACTORM_Pos
#define LL_PRCM_SYSCLK_FACTORM_End   (LL_PRCM_SYSCLK_FACTORM_Pos + 3U)

#if (CONFIG_CHIP_ARCH_VER == 2)
#define LL_PRCM_SYSCLK_FACTORM_5   (0x0U)
#define LL_PRCM_SYSCLK_FACTORM_6   (0x1U)
#define LL_PRCM_SYSCLK_FACTORM_7   (0x2U)
#define LL_PRCM_SYSCLK_FACTORM_8   (0x3U)
#define LL_PRCM_SYSCLK_FACTORM_9   (0x4U)
#elif (CONFIG_CHIP_ARCH_VER == 3)
#define LL_PRCM_SYSCLK_FACTORM_4   (0x0U)
#define LL_PRCM_SYSCLK_FACTORM_5   (0x1U)
#define LL_PRCM_SYSCLK_FACTORM_6   (0x2U)
#define LL_PRCM_SYSCLK_FACTORM_7   (0x3U)
#define LL_PRCM_SYSCLK_FACTORM_9   (0x4U)
#endif /* CONFIG_CHIP_ARCH_VER */

#define LL_PRCM_SYSCLK_FACTORN_Pos      (0U)
#define LL_PRCM_SYSCLK_FACTORN_Msk      (0xFU << LL_PRCM_SYSCLK_FACTORN_Pos)
#define LL_PRCM_SYSCLK_FACTORN_Start    LL_PRCM_SYSCLK_FACTORN_Pos
#define LL_PRCM_SYSCLK_FACTORN_End      (LL_PRCM_SYSCLK_FACTORN_Pos + 3U)
#define LL_PRCM_SYSCLK_FACTORN_1        (0x0U)
#define LL_PRCM_SYSCLK_FACTORN_2        (0x1U)
#define LL_PRCM_SYSCLK_FACTORN_3        (0x2U)
#define LL_PRCM_SYSCLK_FACTORN_4        (0x3U)
#define LL_PRCM_SYSCLK_FACTORN_5        (0x4U)
#define LL_PRCM_SYSCLK_FACTORN_6        (0x5U)
#define LL_PRCM_SYSCLK_FACTORN_7        (0x6U)
#define LL_PRCM_SYSCLK_FACTORN_8        (0x7U)
#define LL_PRCM_SYSCLK_FACTORN_9        (0x8U)
#define LL_PRCM_SYSCLK_FACTORN_10       (0x9U)
#define LL_PRCM_SYSCLK_FACTORN_11       (0xAU)
#define LL_PRCM_SYSCLK_FACTORN_12       (0xBU)
#define LL_PRCM_SYSCLK_FACTORN_13       (0xCU)
#define LL_PRCM_SYSCLK_FACTORN_14       (0xDU)
#define LL_PRCM_SYSCLK_FACTORN_15       (0xEU)
#define LL_PRCM_SYSCLK_FACTORN_16       (0xFU)

#endif // __SYS_PLL_CLOCK_H__