#ifndef __SYS_PLL_CTRL_H__
#define __SYS_PLL_CTRL_H__

#include "LL_base.h"
#include "LL_PRCM_def.h"

/* 
 * fOUT = fHOSC * N.f / M, must be in range of 960 ~ 1920 Mhz
 * [30:29] = DPLL_DITHER ( DPLL_DITHER_DISABLE ?)
 * [28:13] = DPLL_FRAC ( f ), Vfrac = f * (2^16) 
 * [12:12] = DPLL_FRAC_CTRL
 * [11:4]  = DPLL_NDIV ( N )
 * [3:0]   = FACTOR_M ( M)

typedef enum {
#if (CONFIG_CHIP_ARCH_VER == 2)
	PRCM_SYS_PLL_PARAM_HOSC24M    = 0x60000501U,
	PRCM_SYS_PLL_PARAM_HOSC26M    = 0x1B13B491U,
	PRCM_SYS_PLL_PARAM_HOSC40M    = 0x60000301U,
	PRCM_SYS_PLL_PARAM_HOSC52M    = 0x1D89D241U
#elif (CONFIG_CHIP_ARCH_VER == 3)
	PRCM_SYS_PLL_PARAM_HOSC24M    = 0x60000281U,
	PRCM_SYS_PLL_PARAM_HOSC26M    = 0x1D89D241U,
	PRCM_SYS_PLL_PARAM_HOSC40M    = 0x60000181U,
	PRCM_SYS_PLL_PARAM_HOSC32M    = 0x600001E1U
#endif
} PRCM_SysPLLParam;

 */

#define LL_PRCM_PLL_DPLL_DITHER_Pos     (29U)
#define LL_PRCM_PLL_DPLL_DITHER_Msk     (0x3U << LL_PRCM_PLL_DPLL_DITHER_Pos)
#define LL_PRCM_PLL_DPLL_DITHER_Start   (LL_PRCM_PLL_DPLL_DITHER_Pos)
#define LL_PRCM_PLL_DPLL_DITHER_End     (LL_PRCM_PLL_DPLL_DITHER_Pos + 1U)

#define LL_PRCM_PLL_DPLL_FRAC_Pos       (13U)
#define LL_PRCM_PLL_DPLL_FRAC_Msk       (0xFFFFU << LL_PRCM_PLL_DPLL_FRAC_Pos)
#define LL_PRCM_PLL_DPLL_FRAC_Start     (LL_PRCM_PLL_DPLL_FRAC_Pos)
#define LL_PRCM_PLL_DPLL_FRAC_End       (LL_PRCM_PLL_DPLL_FRAC_Pos + 15U)

#define LL_PRCM_PLL_BIT_DPLL_FRAC_CTRL  LL_bit(12)

#define LL_PRCM_PLL_DPLL_NDIV_Pos       (4U)
#define LL_PRCM_PLL_DPLL_NDIV_Msk       (0xFFU << LL_PRCM_PLL_DPLL_NDIV_Pos)
#define LL_PRCM_PLL_DPLL_NDIV_Start     (LL_PRCM_PLL_DPLL_NDIV_Pos)
#define LL_PRCM_PLL_DPLL_NDIV_End       (LL_PRCM_PLL_DPLL_NDIV_Pos + 7U)

#define LL_PRCM_PLL_FACTOR_M_Pos        (0U)
#define LL_PRCM_PLL_FACTOR_M_Msk        (0xFU << LL_PRCM_PLL_FACTOR_M_Pos)
#define LL_PRCM_PLL_FACTOR_M_Start      (LL_PRCM_PLL_FACTOR_M_Pos)
#define LL_PRCM_PLL_FACTOR_M_End        (LL_PRCM_PLL_FACTOR_M_Pos + 3U)

#endif // __SYS_PLL_CTRL_H__